### ISSUE TITLE
no icon on Gnome 3.32 (Ubuntu 19.04)

### ISSUE THREAD

**Issue by legluondunet** [meghprkh/force-quit#10]
Hello,
the extension is activated but I have no icon since I upgraded to Ubuntu 19.04.
Thank you for your help.

**Comment by meghprkh** [comment]
Hi @legluondunet ,

Thanks for reporting the issue. It has been fixed with adc2548

You can either manually patch `~/.local/share/gnome-shell/extensions/fq@megh/extension.js` or wait for it to get reviewed [here](https://extensions.gnome.org/review/10156) (takes 2-3 days) and then update it via the site.
